DEEPSORT:
  # new door
  MODEL_TYPE: "mobilenetv2_x1_0"
  #  109
  # MODEL_TYPE: "mobilenetv2_x1_0"
  MAX_DIST: 0.1 # The matching threshold. Samples with larger distance are considered an invalid match
  MIN_CONFIDENCE: 0.5 # Minimum class confidence to consider
  MAX_IOU_DISTANCE: 0.8 # Gating threshold. Associations with cost larger than this value are disregarded.
  MAX_AGE: 30 # Maximum number of missed misses before a track is deleted
  N_INIT: 3 # Number of frames that a track remains in initialization phase
  NN_BUDGET: 100 # Maximum size of the appearance descriptors gallery
  

# model tracking https://kaiyangzhou.github.io/deep-person-reid/MODEL_ZOO