ANALYZER:
  MAX_CHANNEL: 3
  MIN_LENGTH_UPDATE_BUFFER: 20
  #MAX_LENGTH_UPDATE_BUFFER: 1000
  MAX_LIVE_POLYGON_COUNT: 8
  LENGTH_CHECK_POLYGON: 50
#    new door
  PLACE_TEST: [
        [[400, 500],[600, 200], [800, 200], [750, 500]], 
        [[790, 500], [830, 200], [1100,200], [1150, 500]], 
        [[1190, 500], [1130, 200], [1300,200], [1550, 500]]
  ]


  SHOW_YOLO_RESULT: False

   